name: Deploy to GitHub Pages

on:
  # Dispara a action toda vez que houver um push na branch main
  push:
    branches: ["main"]

  # Permite rodar essa action manualmente pela aba Actions do Github
  workflow_dispatch:

# Permissões necessárias para publicar no Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy simultâneo, ignorando os anteriores
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Job de Deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
